version: "3"
services:
  web:
    build: .
    volumes:
      - .:/go/src/github.com/mjelonek92/go-todo-app
    working_dir: /go/src/github.com/mjelonek92/go-todo-app
    command: fresh
    environment: 
      - TODO_DB_HOST=db
    links:
      - db
    ports:
      - 8000:8080
  db:
    image: postgres:10.3-alpine
    environment: 
      - POSTGRES_USER=tododb
      - POSTGRES_PASSWORD=tododb
      - POSTGRES_DB=tododb
    ports:
      - 5432:5432
    volumes:
      - ./app/models/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
